version: "3"
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: book
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            TZ: "Asia/Singapore"
        ports:
            - 5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
volumes:
    dbdata:
